In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


path = "dataset/prep_time_dataset.csv" # paste dataset path here

df = pd.read_csv(path)

#preview data
df.head()

,storeid,requested_delivery_time,cuisine_group,number_of_items,city,country,latitude,longitude,store_age,prep_time_minutes
0,257666,2025-02-09 20:37:00,quick restaurant service,4.0,Dammam,Saudi Arabia,26.29046,50.03895,3.5,12.655835
1,502320,2025-05-16 22:42:00,restaurant,3.0,Jeddah,Saudi Arabia,21.42572,39.10790,1.0,32.610267
2,791781,2025-05-17 22:35:00,restaurant,5.0,Zarqa,Jordan,32.09914,36.00508,2.2,31.552766
3,785024,2025-01-29 20:03:00,delivery,3.0,Dammam,Saudi Arabia,26.47987,50.16373,4.0,40.190545
4,695724,2025-03-08 18:35:00,quick restaurant service,2.0,Riyadh,Saudi Arabia,24.73557,46.54722,3.5,14.774723

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   storeid                  50000 non-null  int64
 1   requested_delivery_time  49250 non-null  str
 2   cuisine_group            49000 non-null  str
 3   number_of_items          48000 non-null  float64
 4   city                     48500 non-null  str
 5   country                  49000 non-null  str
 6   latitude                 48750 non-null  float64
 7   longitude                48750 non-null  float64
 8   store_age                48250 non-null  float64
 9   prep_time_minutes        49000 non-null  float64
dtypes: float64(5), int64(1), str(4)
memory usage: 3.8 MB

In [4]:
df.describe()

,storeid,number_of_items,latitude,longitude,store_age,prep_time_minutes
count,50000.000000,48000.000000,48750.000000,48750.000000,48250.000000,49000.000000
mean,550707.113160,4.891083,27.311053,40.082115,2.679080,26.697425
std,249199.275592,15.859370,4.189162,5.238615,2.615381,42.249401
min,106626.000000,-5.000000,0.000000,0.000000,0.100000,0.010944
25%,345017.000000,3.000000,24.523370,35.908890,1.200000,13.649909
50%,545558.000000,4.000000,26.415370,39.213940,2.300000,21.413034
75%,763226.000000,6.000000,31.990750,39.965800,3.500000,33.168733
max,996495.000000,857.000000,50.222580,50.263650,119.939543,2722.608585

In [5]:
# check how many unique stores we have
df["storeid"].nunique()

350